docker:
  image: yegor256/rultor-image:1.20.0
assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
install: |-
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle install
    rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" zold-score.gemspec
    git add zold-score.gemspec
    git commit -m "Version set to ${tag}"
    gem build zold-score.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle install
    rake
